### ISSUE TITLE
Support for ESP32

### ISSUE THREAD

**Issue by aly-fly** [dushyantahuja/IPGeolocation#3]
I recommend adding a few (#ifdef) lines in the beginning to automatically select between ESP8266 and ESP32. To make library compatible with both chipsets. Currently I have to copy library to my project and make all necessary adjustments to run on ESP32. This way library is disconnected from any future updates...

**Comment by dushyantahuja** [comment]
I don't use ESP32, so not sure what would be needed. If you want to paste your modified code, I'd be happy to review and include. Thanks

**Comment by mats-nk** [comment]
This is what is needed:
`#ifdef ESP8266`
`  #include <ESP8266WIFI.h>`
`#elif defined(ESP32)`
`  #include <WiFi.h>`
`#else`
`  #error "Not a ESP8266 or ESP32 MCU"`
`#endif`

Since ESP8266 uses `ESP8266WIFI.h` and ESP32 uses `WiFi.h`. So to detect if the board choosen in boardmanager is of one or the other you just add the above lines.

**Comment by mats-nk** [comment]
And while your at it, add `/` to `gitignore` so it looks like this `.vscode/`

**Comment by dushyantahuja** [comment]
Thanks updated
https://github.com/dushyantahuja/IPGeolocation/commit/86e1a7d5ab980636042894e5df6d82fb37b36800
