### ISSUE TITLE
Need help with using this library

### ISSUE THREAD

**Issue by vjeko2404** [dushyantahuja/IPGeolocation#5]
Hello,

thank you for your work but sadly, the library does not work anymore. 
If you don plan to maintain it, please delete it because its very missleading.
Thank you!

EDIT: Please ignore what I wrote. I was very frustrated with the connection problems

**Comment by dushyantahuja** [comment]
It still works for me. As a matter of fact I use it for many of my small projects. If you tell me what's not working for you, I can try to help.

**Comment by vjeko2404** [comment]
I want to sincerely apologize for my words. You definitely did not deserve such a way just because I am limited with knowledge of the ESP-01 module.

Unfortunately, yesterday I was frustrated by the failures and I reacted as I did, taking it out on you. I feel bad about it today.

Today I'm going with a new approach. Maybe the problem is that I'm using WifiManager by tzapu or NTP server for accurate time, I'll try some new ideas.

But even with your code example I can't retrieve the data.
Wlan connects, but after a while the Serialoutput result is:

```
Connected
null
null
null
null
0.00
```

Below is a sketch. If you have any ideas, I would be grateful.
I will try to clean the libraries because I have no idea what the problem could be.

```
#include <Arduino.h>
#include <ESP8266WiFi.h>

#define DEBUG
#include "IPGeolocation.h"


// Replace with your wifi credentials
const char * ssid = "UPC1292692";
const char * password = "*************";

// Get an API Key by registering on
// https://ipgeolocation.io
// OR
// https://app.abstractapi.com/api/ip-geolocation/


String Key = "*********************"; //is for the public and this issue hidden

void setup() {
  // put your setup code here, to run once:
  Serial.begin(9600);
  WiFi.mode(WIFI_STA);
  WiFi.begin(ssid, password);
  if (WiFi.waitForConnectResult() != WL_CONNECTED) {
      Serial.println("WiFi Failed");
      while(1) {
          delay(1000);
      }
  }
  else {
    Serial.print("Connected");
  }
  IPGeolocation location(Key,"ABSTRACT");
  IPGeo IPG;
  location.updateStatus(&IPG);
  Serial.println(IPG.city);
  Serial.println(IPG.country);
  Serial.println(IPG.country_code);
  Serial.println(IPG.tz);
  Serial.println(IPG.offset);
  Serial.println(location.getResponse());
}
void loop() {
}
```

EDIT: Forgot to mention, that I am trying to get the location with Abstract API

**Comment by dushyantahuja** [comment]
The code looks fine - however will need more information to debug; 
1. what is the serial output you're getting when your ESP starts - please paste that
2. what do you get if you paste this in your browser: https://ipgeolocation.abstractapi.com/v1/?api_key=<yourAPIkey>

Replace yourAPIKey with the key you've received from the abtractapi website

**Comment by BaltasarParreira** [comment]
Hi, @dushyantahuja your library needs some modifications so it works at least for using abstractapi.com.

1- the URL they use is not app.abstractapi.com but ipgeolocation.abstractapi.com so need to change this on IPGeolocation.cpp file at line 30.

2- I was not getting any connection even after changing the URL as on step 1, so I had to add some wait on connecting to it like this (before line 60 on IPGeolocation.cpp file also):
```
    int timeout = millis() + 5000;
    while (httpsClient.available() == 0) {
      if (timeout - millis() < 0) {
        DEBUGPRINT(">>> client timeout !");
        httpsClient.stop();
        return;
      }
    }
```

3- On the same file I had to change line 61 (before adding the code from step 2, after this line number will move up depending blank lines, etc.) from this:
```while (httpsClient.connected()) {```
to: 
```while (httpsClient.available()) {```

4- Still on the same file another change similar to the one in step 3 but in line 72 (again line number moves further with the change from step 2) from this:
```while(httpsClient.connected()){```
to:
```while (httpsClient.available()) {```

NOTE: Since line numbers change with adding the code from step 2 I recommend for being easier and to the less expert users changing the code on the other steps and in the end add the code as on step 2 !!!

**Comment by dushyantahuja** [comment]
I've never used abstractapi - can you raise a pull request and I'll merge
it

Regards

**Comment by BaltasarParreira** [comment]
@dushyantahuja 
Hi, pull request as you requested, done.  ; )

**Comment by dushyantahuja** [comment]
Great. I'll review and merge.

**Comment by dushyantahuja** [comment]
Merged - thanks for the pull request
